-- https://school.programmers.co.kr/learn/courses/30/lessons/164671
SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD as A JOIN USED_GOODS_FILE as B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (SELECT VIEWS FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1 )
ORDER BY B.FILE_ID DESC