-- # -- 코드를 입력하세요
-- # SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
-- # FROM REST_INFO
-- # WHERE FOOD_TYPE in (SELECT FOOD_TYPE
-- #                     FROM REST_INFO
-- #                     GROUP BY FOOD_TYPE
-- #                     HAVING FAVORITES = MAX(FAVORITES))
-- # ORDER BY FOOD_TYPE DESC

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT *,
      RANK()OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) as R
      FROM REST_INFO) as a
WHERE R = 1
ORDER BY FOOD_TYPE DESC